openapi: 3.1.0
info:
  title: Reference Search API
  version: 1.0.0
  description: |
    This API allows GPT to search trusted domains 
    (openai.com, cookbook.openai.com, docs.stripe.com, react.dev, shopify.dev)
    and return documentation, tutorials, and sample code.
servers:
  - url: https://mockgptapi.onrender.com
paths:
  /search:
    get:
      operationId: searchReferenceMaterials
      summary: Search trusted reference materials
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            description: Search keyword (e.g. 'LangChain agent tutorial')
      responses:
        '200':
          description: A list of search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  schemas:
    SearchResult:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
          format: uri
        snippet:
          type: string
      required: [title, url]
    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
      required: [results]
